; ASC3 File generated by ScAIEdit III
;
; Script name : Terran Expansion Custom Level

script_name Terran Expansion Custom Level
script_id TMCx

start_town
transports_off
farms_notiming
groundmap_jump block1
goto block2

:block1
build 1 command_center 150
wait_buildstart 1 command_center
build 4 scv 130
wait_buildstart 4 scv
build 7 scv 80
wait_buildstart 7 scv
build 1 barracks 80
wait_buildstart 1 barracks
build 8 scv 80
wait_buildstart 8 scv
build 1 supply_depot 80
wait_buildstart 1 supply_depot
build 10 scv 80
wait_buildstart 10 scv
train 1 marine
defenseuse_gg 1 marine
defenseuse_ag 1 marine
build 11 scv 80
wait_buildstart 11 scv
build 1 refinery 80
wait_buildstart 1 refinery
build 12 scv 80
wait_buildstart 12 scv
train 2 marine
build 2 barracks 80
wait_buildstart 2 barracks
build 13 scv 80
wait_buildstart 13 scv
train 3 marine
build 2 supply_depot 80
wait_buildstart 2 supply_depot
build 14 scv 80
wait_buildstart 14 scv
train 4 marine
capt_expand
build 1 academy 80
wait_buildstart 1 academy
multirun block3
defensebuild_gg 1 firebat
defenseuse_gg 1 firebat
build 15 scv 80
wait_buildstart 15 scv
train 6 marine
build 16 scv 80
wait_buildstart 16 scv
build 3 supply_depot 80
wait_buildstart 3 supply_depot
farms_timing
train 8 marine
build 17 scv 80
wait_buildstart 17 scv
place_guard medic 0
place_guard medic 2
train 2 medic
build 18 scv 80
wait_buildstart 18 scv
build 1 bunker 80
wait_buildstart 1 bunker
race_jump block4 block5 block5

:block4
define_max 30 scv
define_max 24 marine
define_max 8 medic
define_max 8 siege_tank
define_max 4 goliath
define_max 6 wraith
define_max 3 dropship
define_max 7 battlecruiser
define_max 5 science_vessel
define_max 4 valkyrie
define_max 10 ghost
define_max 1 nuclear_missile
define_max 255 firebat
define_max 255 vulture
train 10 marine
build 19 scv 80
wait_buildstart 19 scv
train 11 marine
build 20 scv 80
wait_buildstart 20 scv
train 12 marine
train 4 medic
train 14 marine
attack_add 12 marine
attack_add 3 medic
attack_prepare
defensebuild_gg 1 marine
defensebuild_ag 1 marine
build 1 factory 80
wait_buildstart 1 factory
build 21 scv 80
wait_buildstart 21 scv
train 16 marine
build 22 scv 80
wait_buildstart 22 scv
build 1 machine_shop 80
wait_buildstart 1 machine_shop
train 18 marine
build 23 scv 80
wait_buildstart 23 scv
defensebuild_gg 1 vulture
defenseuse_gg 1 vulture
build 2 bunker 80
wait_buildstart 2 bunker
build 24 scv 80
wait_buildstart 24 scv
build 1 comsat_station 80
wait_buildstart 1 comsat_station
build 25 scv 80
wait_buildstart 25 scv

:block25
train 6 siege_tank
attack_do
attack_clear
attack_add 5 siege_tank
attack_add 12 marine
attack_add 3 medic
attack_prepare
build 1 armory 80
wait_buildstart 1 armory
multirun block6
defensebuild_gg 1 goliath
defenseuse_gg 1 goliath
defensebuild_ag 1 goliath
defenseuse_ag 1 goliath
expand 2 block7
build 1 starport 80
wait_buildstart 1 starport
build 1 control_tower 80
wait_buildstart 1 control_tower
multirun block8
build 1 science_facility 80
wait_buildstart 1 science_facility
place_guard science_vessel 0
multirun block9
train 1 dropship
check_transports
defensebuild_aa 1 valkyrie
defenseuse_aa 1 valkyrie
defensebuild_ag 1 valkyrie
defenseuse_ag 1 valkyrie
defensebuild_aa 1 wraith
defenseuse_aa 1 wraith
defensebuild_ga 1 wraith
defenseuse_ga 1 wraith
defensebuild_ag 1 wraith
defenseuse_ag 1 wraith
defensebuild_gg 1 wraith
defenseuse_gg 1 wraith
build 1 covert_ops 80
wait_buildstart 1 covert_ops
multirun block10
defensebuild_gg 1 ghost
defenseuse_gg 1 ghost
defensebuild_ag 1 ghost
defenseuse_ag 1 ghost
place_guard ghost 0
place_guard ghost 1
place_guard ghost 2
build 2 armory 80
wait_buildstart 2 armory
train 4 ghost
build 2 starport 80
wait_buildstart 2 starport
wait 1350

build 2 control_tower 80
wait_buildstart 2 control_tower
build 2 factory 80
wait_buildstart 2 factory
wait 1350

build 2 machine_shop 80
wait_buildstart 2 machine_shop
upgrade 1 goliath_range 30
expand 3 block7
build 2 science_facility 80
wait_buildstart 2 science_facility
wait 1350

build 1 physics_lab 80
wait_buildstart 1 physics_lab
defensebuild_aa 1 battlecruiser
defenseuse_aa 1 battlecruiser
defensebuild_ga 1 battlecruiser
defenseuse_ga 1 battlecruiser
defensebuild_ag 1 battlecruiser
defenseuse_ag 1 battlecruiser
defensebuild_gg 1 battlecruiser
defenseuse_gg 1 battlecruiser
multirun block11

:block12
train 20 marine
train 2 wraith
train 5 siege_tank
train 4 wraith
train 4 goliath
train 6 wraith
train 4 ghost
train 1 battlecruiser
train 4 medic
train 4 battlecruiser
attack_do
attack_clear
attack_add 4 battlecruiser
attack_add 6 wraith
attack_add 2 valkyrie
attack_add 3 siege_tank
attack_add 2 goliath
attack_add 3 ghost
attack_add 10 marine
attack_add 2 medic
attack_prepare
wait 3600

goto block12

:block5
define_max 30 scv
define_max 24 marine
define_max 8 medic
define_max 8 siege_tank
define_max 8 goliath
define_max 6 wraith
define_max 3 dropship
define_max 6 battlecruiser
define_max 7 science_vessel
define_max 6 valkyrie
define_max 8 firebat
define_max 255 ghost
define_max 255 nuclear_missile
define_max 255 vulture
train 2 firebat
build 19 scv 80
wait_buildstart 19 scv
train 3 firebat
build 20 scv 80
wait_buildstart 20 scv
train 4 firebat
train 4 medic
train 12 marine
attack_add 10 marine
attack_add 4 firebat
attack_add 3 medic
attack_prepare
defensebuild_gg 1 marine
defensebuild_ag 1 marine
enemyowns_jump citadel_of_adun block13
goto block14

:block13
build 1 engineering_bay 80
wait_buildstart 1 engineering_bay
build 1 comsat_station 80
wait_buildstart 1 comsat_station
multirun block15

:block14
build 1 factory 80
wait_buildstart 1 factory
build 21 scv 80
wait_buildstart 21 scv
train 13 marine
train 5 firebat
build 22 scv 80
wait_buildstart 22 scv
build 1 machine_shop 80
wait_buildstart 1 machine_shop
train 14 marine
train 6 firebat
build 23 scv 80
wait_buildstart 23 scv
defensebuild_gg 1 vulture
defenseuse_gg 1 vulture
build 2 bunker 80
wait_buildstart 2 bunker
build 24 scv 80
wait_buildstart 24 scv
build 1 comsat_station 80
wait_buildstart 1 comsat_station
build 25 scv 80
wait_buildstart 25 scv
build 1 engineering_bay 80
wait_buildstart 1 engineering_bay
multirun block16
multirun block15
race_jump block17 block17 block18

:block17
train 1 siege_tank
build 26 scv 80
wait_buildstart 26 scv
defensebuild_gg 1 siege_tank
defenseuse_gg 1 siege_tank
tech siege_mode 80
train 2 siege_tank
build 27 scv 80
wait_buildstart 27 scv
train 16 marine
train 3 siege_tank
build 28 scv 80
wait_buildstart 28 scv
panic block7
expand 1 block7
build 30 scv 80
wait_buildstart 30 scv
train 20 marine
train 5 siege_tank
attack_do
attack_clear
attack_add 4 siege_tank
attack_add 10 marine
attack_add 4 firebat
attack_add 3 medic
attack_prepare
build 1 armory 80
wait_buildstart 1 armory
multirun block6
defensebuild_gg 1 goliath
defenseuse_gg 1 goliath
defensebuild_ag 1 goliath
defenseuse_ag 1 goliath
expand 2 block7
build 1 starport 80
wait_buildstart 1 starport
build 1 control_tower 80
wait_buildstart 1 control_tower
multirun block8
build 1 science_facility 80
wait_buildstart 1 science_facility
place_guard science_vessel 0
multirun block9
defenseuse_gg 1 ghost
defenseuse_ag 1 ghost
train 1 dropship
check_transports
defensebuild_aa 1 valkyrie
defenseuse_aa 1 valkyrie
defensebuild_ag 1 valkyrie
defenseuse_ag 1 valkyrie
defensebuild_aa 1 wraith
defenseuse_aa 1 wraith
defensebuild_ga 1 wraith
defenseuse_ga 1 wraith
defensebuild_ag 1 wraith
defenseuse_ag 1 wraith
defensebuild_gg 1 wraith
defenseuse_gg 1 wraith
build 2 armory 80
wait_buildstart 2 armory
train 1 science_vessel
build 2 starport 80
wait_buildstart 2 starport
wait 1350

build 2 control_tower 80
wait_buildstart 2 control_tower
build 2 factory 80
wait_buildstart 2 factory
wait 1350

build 2 machine_shop 80
wait_buildstart 2 machine_shop
upgrade 1 goliath_range 30
expand 3 block7
build 1 physics_lab 80
wait_buildstart 1 physics_lab
defensebuild_aa 1 battlecruiser
defenseuse_aa 1 battlecruiser
defensebuild_ga 1 battlecruiser
defenseuse_ga 1 battlecruiser
defensebuild_ag 1 battlecruiser
defenseuse_ag 1 battlecruiser
defensebuild_gg 1 battlecruiser
defenseuse_gg 1 battlecruiser
multirun block11

:block19
train 20 marine
train 2 valkyrie
train 4 siege_tank
train 4 firebat
train 4 valkyrie
train 4 goliath
train 4 medic
train 4 wraith
train 4 battlecruiser
attack_do
attack_clear
attack_add 4 battlecruiser
attack_add 4 wraith
attack_add 4 valkyrie
attack_add 3 siege_tank
attack_add 4 goliath
attack_add 10 marine
attack_add 2 firebat
attack_add 2 medic

:block24
attack_prepare
wait 3600


:block23
resources_jump 4000 2500 block19
resources_jump 3000 2200 block20
resources_jump 1900 800 block21
resources_jump 1400 100 block22
wait 900

goto block23

:block20
train 4 battlecruiser
train 4 valkyrie
train 6 wraith
attack_do
attack_clear
attack_add 4 battlecruiser
attack_add 6 wraith
attack_add 4 valkyrie
goto block24

:block21
train 4 siege_tank
train 4 goliath
train 10 marine
train 4 firebat
train 3 medic
attack_do
attack_clear
attack_add 4 siege_tank
attack_add 4 goliath
attack_add 10 marine
attack_add 4 firebat
attack_add 3 medic
goto block24

:block22
train 24 marine
train 4 medic
attack_do
attack_clear
attack_add 24 marine
attack_add 4 medic
goto block24

:block15
wait_build 1 engineering_bay
build 1 missile_turret 80
wait_build 1 missile_turret
wait 450

build 2 missile_turret 70
wait_build 2 missile_turret
wait 450

build 3 missile_turret 70
wait_build 3 missile_turret
wait 450

build 4 missile_turret 70
wait_build 4 missile_turret
wait 450

build 5 missile_turret 70
wait_build 5 missile_turret
wait 450

stop

:block18
define_max 30 scv
define_max 24 marine
define_max 8 medic
define_max 8 siege_tank
define_max 6 goliath
define_max 6 wraith
define_max 3 dropship
define_max 5 battlecruiser
define_max 7 science_vessel
define_max 4 valkyrie
define_max 6 firebat
define_max 9 ghost
define_max 1 nuclear_missile
define_max 5 vulture
train 1 vulture
tech spider_mines 80
build 2 factory 80
wait_buildstart 2 factory
upgrade 1 vulture_speed 30
build 26 scv 80
wait_buildstart 26 scv
train 10 marine
train 2 vulture
build 27 scv 80
wait_buildstart 27 scv
train 12 marine
train 3 vulture
build 28 scv 80
wait_buildstart 28 scv
train 14 marine
train 4 vulture
build 29 scv 80
wait_buildstart 29 scv
train 16 marine
train 5 vulture
build 30 scv 80
wait_buildstart 30 scv
train 1 siege_tank
defensebuild_gg 1 siege_tank
defenseuse_gg 1 siege_tank
tech siege_mode 80
train 2 siege_tank
train 16 marine
train 3 siege_tank
panic block7
expand 1 block7
train 20 marine
train 4 siege_tank
goto block25

:block27
wait 7200

expand 99 block26
goto block27

:block2
define_max 30 scv
define_max 16 marine
define_max 5 medic
define_max 10 goliath
define_max 6 wraith
define_max 3 dropship
define_max 10 battlecruiser
define_max 4 science_vessel
define_max 6 valkyrie
define_max 5 ghost
define_max 255 firebat
define_max 255 siege_tank
define_max 255 nuclear_missile
define_max 255 vulture
multirun block28
goto block29

:block28
notowns_jump barracks block30
goto block31

:block30
wait 300

goto block28

:block31
defenseuse_gg 1 marine
defenseuse_ag 1 marine

:block34
notowns_jump factory block32
goto block33

:block32
wait 300

goto block34

:block33
defensebuild_gg 1 marine
defensebuild_gg 1 goliath
defenseuse_gg 1 goliath
defensebuild_ag 1 marine
defensebuild_ag 1 goliath
defenseuse_ag 1 goliath
wait_train 1 valkyrie
defensebuild_aa 1 valkyrie
defenseuse_aa 1 valkyrie
defensebuild_ag 1 valkyrie
defenseuse_ag 1 valkyrie
wait_train 1 wraith
defensebuild_aa 1 wraith
defenseuse_aa 1 wraith
defensebuild_ga 1 wraith
defenseuse_ga 1 wraith
defensebuild_ag 1 wraith
defenseuse_ag 1 wraith
defensebuild_gg 1 wraith
defenseuse_gg 1 wraith
wait_train 1 battlecruiser
defensebuild_aa 1 battlecruiser
defenseuse_aa 1 battlecruiser
defensebuild_ga 1 battlecruiser
defenseuse_ga 1 battlecruiser
defensebuild_ag 1 battlecruiser
defenseuse_ag 1 battlecruiser
defensebuild_gg 1 battlecruiser
defenseuse_gg 1 battlecruiser
stop

:block29
build 1 command_center 150
wait_buildstart 1 command_center
build 4 scv 130
wait_buildstart 4 scv
build 8 scv 80
wait_buildstart 8 scv
build 1 supply_depot 80
wait_buildstart 1 supply_depot
capt_expand
random_jump 64 block35
build 11 scv 80
wait_buildstart 11 scv
build 1 barracks 80
wait_buildstart 1 barracks
build 12 scv 80
wait_buildstart 12 scv
build 1 refinery 80
wait_buildstart 1 refinery
build 14 scv 80
wait_buildstart 14 scv
build 2 supply_depot 80
wait_buildstart 2 supply_depot
build 15 scv 80
wait_buildstart 15 scv
train 1 marine
build 17 scv 80
wait_buildstart 17 scv
train 2 marine
build 1 factory 80
wait_buildstart 1 factory
build 18 scv 80
wait_buildstart 18 scv
train 3 marine
build 3 supply_depot 80
wait_buildstart 3 supply_depot
farms_timing
build 19 scv 80
wait_buildstart 19 scv
train 4 marine
build 20 scv 80
wait_buildstart 20 scv
build 2 barracks 80
wait_buildstart 2 barracks
train 5 marine

:block48
build 21 scv 80
wait_buildstart 21 scv
build 1 machine_shop 80
wait_buildstart 1 machine_shop
build 22 scv 80
wait_buildstart 22 scv
build 1 academy 80
wait_buildstart 1 academy
build 23 scv 80
wait_buildstart 23 scv
train 6 marine
build 1 armory 80
wait_buildstart 1 armory
build 24 scv 80
wait_buildstart 24 scv
train 7 marine
build 25 scv 80
wait_buildstart 25 scv
build 1 bunker 80
wait_buildstart 1 bunker
build 26 scv 80
wait_buildstart 26 scv
train 9 marine
build 27 scv 80
wait_buildstart 27 scv
build 2 bunker 80
wait_buildstart 2 bunker
train 10 marine
build 28 scv 80
wait_buildstart 28 scv
build 1 comsat_station 80
wait_buildstart 1 comsat_station
train 12 marine
build 29 scv 80
wait_buildstart 29 scv
train 1 goliath
build 30 scv 80
wait_buildstart 30 scv
upgrade 1 goliath_range 30
upgrade 1 marine_range 70
multirun block36
train 12 marine
train 2 goliath
place_guard medic 0
place_guard medic 0
multirun block3
build 1 starport 80
wait_buildstart 1 starport
train 12 marine
train 3 goliath
build 1 engineering_bay 80
wait_buildstart 1 engineering_bay
multirun block37
train 4 goliath
tech stim_packs 70
build 1 control_tower 80
wait_buildstart 1 control_tower
train 5 goliath
train 1 valkyrie
train 6 goliath
multirun block38
train 7 goliath
train 1 dropship
check_transports
expand 1 block26
panic block26
build 2 starport 80
wait_buildstart 2 starport
train 2 valkyrie
build 2 control_tower 80
wait_buildstart 2 control_tower
expand 1 block26
train 5 valkyrie
build 1 science_facility 80
wait_buildstart 1 science_facility
expand 1 block26
multirun block9
train 5 valkyrie
multirun block8
train 2 wraith
place_guard sciencsse_vessel 0
place_guard science_vessel 2
expand 2 block26
build 3 starport 80
wait_buildstart 3 starport
train 4 wraith
build 1 covert_ops 80
wait_buildstart 1 covert_ops
build 2 science_facility 80
wait_buildstart 2 science_facility
build 3 control_tower 80
wait_buildstart 3 control_tower
train 5 wraith
place_guard ghost 0
place_guard ghost 2
multirun block39
train 6 wraith
build 1 physics_lab 80
wait_buildstart 1 physics_lab
train 1 battlecruiser
multirun block11
attack_do
attack_clear
attack_add 4 goliath
attack_add 8 marine
attack_add 6 wraith
attack_prepare
multirun block40
train 4 battlecruiser
attack_do
attack_clear
multirun block27

:block41
train 10 battlecruiser
attack_add 8 battlecruiser
attack_add 4 valkyrie
attack_prepare
wait 300

attack_do
attack_clear
wait 900

goto block41

:block40
train 12 marine
train 8 goliath
train 6 valkyrie
train 6 wraith
wait 150

goto block40

:block39
wait_build 1 covert_ops
wait_train 1 ghost
tech lockdown 80
wait 4500

upgrade 1 ghost_sight 30
wait 4500

tech personnel_cloaking 30
wait 4500

upgrade 1 ghost_mana 30
stop

:block37
wait_build 1 engineering_bay
wait_train 12 marine
upgrade 1 t_infantry_armor 70
wait 4500

wait_train 12 marine
upgrade 1 t_infantry_weapon 70
wait 4500


:block44
notowns_jump science_facility block42
goto block43

:block42
wait 300

goto block44

:block43
wait_train 12 marine
upgrade 2 t_infantry_armor 70
wait 4500

wait_train 12 marine
upgrade 2 t_infantry_weapon 70
wait 4500

wait_train 12 marine
upgrade 3 t_infantry_armor 70
wait 4500

wait_train 12 marine
upgrade 3 t_infantry_weapon 70
stop

:block36
wait_build 1 armory
upgrade 1 t_vehicle_plating 70
wait 4500

upgrade 1 t_ship_plating 70
wait 4500

upgrade 1 t_ship_weapon 70
wait 4500

upgrade 1 t_vehicle_weapon 70
wait 4500


:block47
notowns_jump science_facility block45
goto block46

:block45
wait 300

goto block47

:block46
upgrade 2 t_ship_plating 70
wait 4500

upgrade 2 t_ship_weapon 70
wait 4500

upgrade 3 t_ship_plating 70
wait 4500

upgrade 3 t_ship_weapon 70
wait 4500

upgrade 2 t_vehicle_plating 70
wait 4500

upgrade 2 t_vehicle_weapon 70
wait 4500

upgrade 3 t_vehicle_plating 70
wait 4500

upgrade 3 t_vehicle_weapon 70
stop

:block35
build 12 scv 80
wait_buildstart 12 scv
build 1 barracks 80
wait_buildstart 1 barracks
build 1 refinery 80
wait_buildstart 1 refinery
build 16 scv 80
wait_buildstart 16 scv
build 2 supply_depot 80
wait_buildstart 2 supply_depot
build 1 factory 80
wait_buildstart 1 factory
build 18 scv 80
wait_buildstart 18 scv
train 1 marine
build 19 scv 80
wait_buildstart 19 scv
train 2 marine
build 3 supply_depot 80
wait_buildstart 3 supply_depot
farms_timing
build 20 scv 80
wait_buildstart 20 scv
train 3 marine
build 1 starport 80
wait_buildstart 1 starport
train 4 marine
build 2 barracks 80
wait_buildstart 2 barracks
train 6 marine
build 1 academy 80
wait_buildstart 1 academy
build 1 control_tower 80
wait_buildstart 1 control_tower
train 9 marine
train 1 dropship
build 1 engineering_bay 80
wait_buildstart 1 engineering_bay
train 11 marine
build 1 comsat_station 80
wait_buildstart 1 comsat_station
train 13 marine
train 2 dropship
train 15 marine
tech stim_packs 80
build 1 armory 80
wait_buildstart 1 armory
train 16 marine
upgrade 1 t_infantry_armor 80
wait_train 2 dropship
wait_train 16 marine
attack_add 16 marine
attack_prepare
goto block48

:block3
wait_build 1 academy
wait_train 8 marine
upgrade 1 marine_range 80
wait 2700

wait_train 1 medic
tech optical_flare 70
wait 2700

wait_train 12 marine
tech stim_packs 80
wait 2700

wait_train 1 medic
upgrade 1 medic_mana 70
wait 2700

wait_train 1 medic
tech restoration 70
stop

:block16
wait_build 1 engineering_bay
wait_train 8 marine
upgrade 1 t_infantry_weapon 80
wait 4500

wait_train 12 marine
upgrade 1 t_infantry_armor 80
wait 4500

wait_build 1 science_facility
wait_train 12 marine
upgrade 2 t_infantry_armor 80
wait 4500

wait_train 12 marine
upgrade 2 t_infantry_weapon 80
wait 4500

wait_train 12 marine
upgrade 3 t_infantry_armor 80
wait 4500

wait_train 12 marine
upgrade 3 t_infantry_weapon 80
stop

:block10
wait_train 1 ghost
tech lockdown 80
wait 4500

wait_train 1 ghost
tech personnel_cloaking 80
wait 4500

wait_train 1 ghost
upgrade 1 ghost_sight 70
wait 4500

wait_train 1 ghost
upgrade 1 ghost_mana 70
stop

:block11
wait_build 1 physics_lab
wait_train 1 battlecruiser
tech yamato_gun 70
wait 4500

wait_train 4 battlecruiser
upgrade 1 battlecruiser_mana 30
stop

:block8
wait_build 1 control_tower
wait_train 1 wraith
tech cloaking_field 70
wait 4500

wait_train 1 wraith
upgrade 1 wraith_mana 30
stop

:block9
wait_build 1 science_facility
race_jump block49 block50 block51

:block49
wait_train 1 science_vessel
tech irradiate 70
wait 2700

wait_train 1 science_vessel
tech emp_shockwave 30
wait 4500

wait_train 1 science_vessel
upgrade 1 science_vessel_mana 30
wait 4500

stop

:block51
wait_train 1 science_vessel
tech emp_shockwave 80
wait 2700

wait_train 1 science_vessel
tech irradiate 30
wait 4500

wait_train 1 science_vessel
upgrade 1 science_vessel_mana 30
wait 4500

stop

:block50
wait_train 1 science_vessel
tech irradiate 80
wait 2700

wait_train 1 science_vessel
tech emp_shockwave 30
wait 4500

wait_train 1 science_vessel
upgrade 1 science_vessel_mana 30
wait 4500

stop

:block38
wait_build 1 engineering_bay
build 1 missile_turret 80
wait_build 1 missile_turret
build 2 missile_turret 70
wait_build 2 missile_turret
build 3 missile_turret 70
wait_build 3 missile_turret
build 4 missile_turret 70
wait_build 4 missile_turret
wait 450

build 5 missile_turret 70
wait_build 5 missile_turret
wait 450

build 6 missile_turret 70
wait_build 6 missile_turret
wait 450

build 7 missile_turret 70
wait_build 7 missile_turret
wait 450

build 8 missile_turret 70
wait_build 8 missile_turret
wait 450

groundmap_jump block52

:block52
build 9 missile_turret 70
wait_build 9 missile_turret
build 10 missile_turret 70
wait_build 10 missile_turret
stop

:block55
wait_build 1 engineering_bay
build 1 missile_turret 80
wait_build 1 missile_turret
build 2 missile_turret 70
wait_build 2 missile_turret
build 3 missile_turret 70
wait_build 3 missile_turret
groundmap_jump block53
build 4 missile_turret 70
wait_build 4 missile_turret

:block53
stop

:block88
wait_build 1 engineering_bay
build 1 missile_turret 80
wait_build 1 missile_turret
build 2 missile_turret 70
wait_build 2 missile_turret
build 3 missile_turret 70
wait_build 3 missile_turret
build 4 missile_turret 70
wait_build 4 missile_turret
groundmap_jump block54
build 5 missile_turret 70
wait_build 5 missile_turret
build 6 missile_turret 70
wait_build 6 missile_turret

:block54
stop

:block6
wait_build 1 armory
wait_train 2 siege_tank
upgrade 1 t_vehicle_weapon 80
wait 3600

wait_train 4 siege_tank
upgrade 1 t_vehicle_plating 80
wait 1800

upgrade 1 t_ship_weapon 80
wait 1800

upgrade 1 t_ship_plating 80
wait 1800

upgrade 2 t_vehicle_weapon 80
wait 1800

upgrade 2 t_vehicle_plating 80
wait 1800

upgrade 2 t_ship_weapon 80
wait 1800

upgrade 2 t_ship_plating 80
wait 1800

upgrade 3 t_vehicle_weapon 80
wait 1800

upgrade 3 t_vehicle_plating 80
wait 1800

upgrade 3 t_ship_weapon 80
wait 1800

upgrade 3 t_ship_plating 80
wait 1800

stop

:block7
start_town
build 1 command_center 80
wait_build 1 command_center
build 2 scv 80
wait_build 2 scv
build 1 bunker 80
wait_buildstart 1 bunker
build 3 scv 80
wait_build 3 scv
multirun block55
build 4 scv 80
wait_build 4 scv
build 5 scv 80
wait_build 5 scv
build 6 scv 80
wait_build 6 scv
build 7 scv 80
wait_build 7 scv

:block58
notowns_jump barracks block56
goto block57

:block56
wait 300

goto block58

:block57
player_need 1 barracks
build 8 scv 80
wait_build 8 scv
build 9 scv 80
wait_build 9 scv
build 10 scv 80
wait_build 10 scv
build 11 scv 80
wait_build 11 scv
build 12 scv 80
wait_build 12 scv
build 13 scv 80
wait_build 13 scv
build 14 scv 80
wait_build 14 scv
build 15 scv 80
wait_build 15 scv
build 16 scv 80
wait_build 16 scv
build 17 scv 80
wait_build 17 scv
build 18 scv 80
wait_build 18 scv
build 19 scv 80
wait_build 19 scv
build 20 scv 80
wait_build 20 scv
build 21 scv 80
wait_build 21 scv
build 22 scv 80
wait_build 22 scv
build 23 scv 80
wait_build 23 scv
build 24 scv 80
wait_build 24 scv
place_guard medic 0
place_guard medic 2
place_guard science_vessel 0
place_guard ghost 0
place_guard ghost 1
place_guard ghost 2
if_owned nuclear_silo block59
notowns_jump comsat_station block59
notowns_jump science_facility block59
notowns_jump covert_ops block59
build 1 nuclear_silo 80
wait_build 1 nuclear_silo
groundmap_jump block60
goto block61

:block60
resources_jump 1000 0 block62
wait 150

goto block60

:block62
build 1 barracks 80
wait_build 1 barracks

:block64
resources_jump 2000 1000 block63
wait 150

goto block64

:block63
build 1 factory 80
wait_buildstart 1 factory
wait 1800

build 1 machine_shop 80
wait_buildstart 1 machine_shop

:block61
resources_jump 3000 2000 block65
wait 150

goto block61

:block65
build 1 starport 80
wait_buildstart 1 starport
wait 1800

build 1 control_tower 80
wait_buildstart 1 control_tower
groundmap_jump block66
goto block67

:block66
notowns_jump science_facility block68
goto block69

:block68
wait 300

goto block66

:block69
player_need 1 science_facility

:block72
notowns_jump covert_ops block70
goto block71

:block70
wait 300

goto block72

:block71
player_need 1 covert_ops

:block67
wait 900

goto block67

:block59
notowns_jump academy block73
goto block74

:block73
wait 300

goto block59

:block74
player_need 1 academy
build 1 comsat_station 80
wait_build 1 comsat_station
groundmap_jump block75
goto block76

:block75
resources_jump 1000 0 block77
wait 150

goto block75

:block77
build 1 barracks 80
wait_build 1 barracks

:block79
resources_jump 2000 1000 block78
wait 150

goto block79

:block78
build 1 factory 80
wait_buildstart 1 factory
wait 1800

build 1 machine_shop 80
wait_buildstart 1 machine_shop

:block76
resources_jump 3000 2000 block80
wait 150

goto block76

:block80
build 1 starport 80
wait_buildstart 1 starport
wait 1800

build 1 control_tower 80
wait_buildstart 1 control_tower
groundmap_jump block81
goto block82

:block81
notowns_jump science_facility block83
goto block84

:block83
wait 300

goto block81

:block84
player_need 1 science_facility

:block87
notowns_jump physics_lab block85
goto block86

:block85
wait 300

goto block87

:block86
player_need 1 physics_lab

:block82
wait 900

goto block82

:block26
start_town
build 1 command_center 80
wait_build 1 command_center
build 2 scv 80
wait_build 2 scv
build 1 bunker 80
wait_buildstart 1 bunker
build 3 scv 80
wait_build 3 scv
multirun block88
build 4 scv 80
wait_build 4 scv
build 5 scv 80
wait_build 5 scv
build 6 scv 80
wait_build 6 scv
build 7 scv 80
wait_build 7 scv

:block91
notowns_jump barracks block89
goto block90

:block89
wait 300

goto block91

:block90
player_need 1 barracks
build 8 scv 80
wait_build 8 scv
build 9 scv 80
wait_build 9 scv
build 10 scv 80
wait_build 10 scv
build 11 scv 80
wait_build 11 scv
build 12 scv 80
wait_build 12 scv
build 13 scv 80
wait_build 13 scv
build 14 scv 80
wait_build 14 scv
build 15 scv 80
wait_build 15 scv
build 16 scv 80
wait_build 16 scv
build 17 scv 80
wait_build 17 scv
build 18 scv 80
wait_build 18 scv
build 19 scv 80
wait_build 19 scv
build 20 scv 80
wait_build 20 scv
build 24 scv 80
wait_build 24 scv

:block94
notowns_jump academy block92
goto block93

:block92
wait 300

goto block94

:block93
player_need 1 academy
place_guard medic 0
build 1 comsat_station 80
wait_buildstart 1 comsat_station
groundmap_jump block95
goto block96

:block95
resources_jump 1000 0 block97
wait 150

goto block95

:block97
build 1 barracks 80
wait_buildstart 1 barracks

:block99
resources_jump 2000 1000 block98
wait 150

goto block99

:block98
build 1 factory 80
wait_buildstart 1 factory
wait 1800

build 1 machine_shop 80
wait_buildstart 1 machine_shop

:block96
resources_jump 3000 2000 block100
wait 150

goto block96

:block100
build 1 starport 80
wait_buildstart 1 starport
wait 1800

build 1 control_tower 80
wait_buildstart 1 control_tower

:block103
notowns_jump science_facility block101
goto block102

:block101
wait 300

goto block103

:block102
player_need 1 science_facility
place_guard science_vessel 0
place_guard ghost 0

:block106
notowns_jump physics_lab block104
goto block105

:block104
wait 300

goto block106

:block105
player_need 1 physics_lab

:block107
wait 900

goto block107
