; ASC3 File generated by ScAIEdit III
;
; Script name : Zerg Expansion Custom Level

script_name Zerg Expansion Custom Level
script_id ZMCx

start_town
transports_off
farms_notiming
groundmap_jump block1
goto block2

:block1
define_max 30 drone
define_max 30 hydralisk
define_max 30 zergling
define_max 14 mutalisk
define_max 10 scourge
define_max 9 lurker
define_max 6 queen
define_max 6 defiler
define_max 5 guardian
define_max 5 devourer
define_max 6 ultralisk
build 1 drone 150
wait_buildstart 1 drone
build 1 hatchery 150
wait_buildstart 1 hatchery
build 1 overlord 130
wait_buildstart 1 overlord
random_jump 32 block3
build 9 drone 80
wait_buildstart 9 drone

:block24
build 2 overlord 80
wait_buildstart 2 overlord
random_jump 192 block4
race_jump block4 block5 block5

:block5
expand 1 block6
build 12 drone 80
wait_buildstart 12 drone
build 1 hatchery 80
wait_buildstart 1 hatchery
build 1 spawning_pool 80
wait_buildstart 1 spawning_pool
defenseuse_gg 1 zergling
build 12 drone 80
wait_buildstart 12 drone
creep 3
build 1 extractor 80
wait_buildstart 1 extractor
creep 3
build 2 creep_colony 80
wait_buildstart 2 creep_colony
build 14 drone 80
wait_buildstart 14 drone
build 1 sunken_colony 80
wait_buildstart 1 sunken_colony
build 3 creep_colony 80
wait_buildstart 3 creep_colony
build 2 sunken_colony 80
wait_buildstart 2 sunken_colony
creep 4
build 4 creep_colony 80
wait_buildstart 4 creep_colony
build 3 overlord 80
wait_buildstart 3 overlord
farms_timing
build 4 sunken_colony 80
wait_buildstart 4 sunken_colony
build 15 drone 80
wait_buildstart 15 drone
goto block7

:block4
build 12 drone 80
wait_buildstart 12 drone
build 2 hatchery 80
wait_buildstart 2 hatchery
build 1 spawning_pool 80
wait_buildstart 1 spawning_pool
defenseuse_gg 1 zergling
build 13 drone 80
wait_buildstart 13 drone
creep 3
build 1 extractor 80
wait_buildstart 1 extractor
creep 3
build 2 creep_colony 80
wait_buildstart 2 creep_colony
build 15 drone 80
wait_buildstart 15 drone
build 1 sunken_colony 80
wait_buildstart 1 sunken_colony
build 3 creep_colony 80
wait_buildstart 3 creep_colony
build 2 sunken_colony 80
wait_buildstart 2 sunken_colony
creep 4
build 4 creep_colony 80
wait_buildstart 4 creep_colony
build 3 overlord 80
wait_buildstart 3 overlord
farms_timing
build 4 sunken_colony 80
wait_buildstart 4 sunken_colony
build 16 drone 80
wait_buildstart 16 drone

:block7
build 1 lair 80
wait_buildstart 1 lair
build 1 hydralisk_den 80
wait_buildstart 1 hydralisk_den
defenseuse_gg 1 hydralisk
defenseuse_ag 1 hydralisk
train 6 zergling
train 5 hydralisk
tech lurker_aspect 80
train 14 hydralisk
place_guard lurker 0
place_guard lurker 1
place_guard lurker 2
train 3 lurker
defensebuild_gg 1 hydralisk
defensebuild_ag 1 hydralisk
defensebuild_gg 1 zergling
defensebuild_gg 1 lurker
multirun block8
build 16 drone 80
wait_buildstart 16 drone
panic block6
expand 1 block6
train 10 hydralisk
train 12 zergling
multirun block9
build 18 drone 80
wait_buildstart 18 drone
multirun block10
train 2 lurker
build 20 drone 80
wait_buildstart 20 drone
train 12 hydralisk
build 22 drone 80
wait_buildstart 22 drone
train 14 hydralisk
build 24 drone 80
wait_buildstart 24 drone
train 16 hydralisk
build 26 drone 80
wait_buildstart 26 drone
train 18 hydralisk
build 28 drone 80
wait_buildstart 28 drone
train 20 hydralisk
build 30 drone 80
wait_buildstart 30 drone
train 22 hydralisk
attack_do
attack_clear
attack_add 20 hydralisk
attack_add 2 lurker
attack_prepare
tech burrowing 30
expand 2 block6
train 12 hydralisk
build 1 queen_nest 80
wait_buildstart 1 queen_nest
place_guard queen 0
place_guard queen 1
place_guard queen 2
multirun block11
build 1 evolution_chamber 80
wait_buildstart 1 evolution_chamber
multirun block12
multirun block13
build 1 spire 80
wait_buildstart 1 spire
multirun block14
train 1 queen
guard_resources zergling
train 12 zergling
train 12 hydralisk
train 6 mutalisk
defensebuild_aa 2 scourge
defenseuse_aa 2 scourge
defensebuild_ag 2 scourge
defenseuse_ag 2 scourge
defensebuild_ag 1 devourer
defenseuse_ag 1 devourer
defensebuild_aa 1 devourer
defenseuse_aa 1 devourer
defensebuild_aa 1 mutalisk
defenseuse_aa 1 mutalisk
defensebuild_ga 1 mutalisk
defenseuse_ga 1 mutalisk
defensebuild_ag 1 mutalisk
defenseuse_ag 1 mutalisk
defensebuild_gg 1 mutalisk
defenseuse_gg 1 mutalisk
build 1 hive 80
wait_buildstart 1 hive
expand 3 block6
train 12 hydralisk
build 1 defiler_mound 80
wait_buildstart 1 defiler_mound
place_guard defiler 0
place_guard defiler 1
place_guard defiler 2
multirun block15
expand 4 block6
multirun block16
build 1 greater_spire 80
wait_buildstart 1 greater_spire
build 1 ultralisk_cavern 80
wait_buildstart 1 ultralisk_cavern
multirun block17
defensebuild_gg 1 ultralisk
defenseuse_gg 1 ultralisk
train 6 mutalisk
train 4 devourer
train 6 mutalisk
train 4 guardian
defensebuild_gg 1 guardian
defenseuse_gg 1 guardian
defensebuild_ga 1 guardian
defenseuse_ga 1 guardian
train 9 mutalisk
train 4 devourer
train 9 mutalisk
train 4 guardian
train 8 scourge
attack_do
attack_clear
attack_add 9 mutalisk
attack_add 4 devourer
attack_add 4 guardian
attack_add 8 scourge
attack_prepare
define_max 60 zergling
train 60 zergling
attack_do
attack_clear
attack_add 60 zergling
attack_prepare
define_max 30 zergling

:block19
attack_prepare
wait 300

attack_do
attack_clear
groundmap_jump block18
train 14 mutalisk
train 4 devourer
train 14 mutalisk
train 4 guardian
wait_train 4 guardian
attack_add 12 mutalisk
attack_add 4 devourer
attack_add 4 guardian
goto block19

:block18
resources_jump 2100 1500 block20
resources_jump 1500 500 block21
resources_jump 1400 300 block22
resources_jump 1000 0 block23
wait 900

goto block19

:block20
train 6 ultralisk
train 12 hydralisk
wait_train 6 ultralisk
attack_add 6 ultralisk
attack_add 12 hydralisk
goto block19

:block21
train 20 hydralisk
attack_add 20 hydralisk
goto block19

:block22
train 12 hydralisk
train 20 zergling
attack_add 20 hydralisk
attack_add 20 zergling
goto block19

:block23
define_max 40 zergling
train 40 zergling
wait_train 40 zergling
attack_add 40 zergling
define_max 30 zergling
goto block19

:block3
build 4 drone 80
wait_buildstart 4 drone
build 1 spawning_pool 80
wait_buildstart 1 spawning_pool
train 6 zergling
attack_add 6 zergling
attack_prepare
build 6 drone 80
wait_buildstart 6 drone
goto block24

:block16
wait 7200

expand 99 block6
goto block16

:block17
notowns_jump ultralisk_cavern block25
goto block26

:block25
wait 300

goto block17

:block26
upgrade 1 ultralisk_armor 70
wait 2700

upgrade 1 ultralisk_speed 70
stop

:block15
wait_train 1 defiler
tech plague 80
wait 2700

upgrade 1 defiler_mana 30
stop

:block14
wait_train 4 mutalisk
upgrade 1 z_flyer_attack 70
wait 4500


:block29
notowns_jump greater_spire block27
goto block28

:block27
wait 300

goto block29

:block28
upgrade 1 z_flyer_carapace 70
wait 4500

upgrade 2 z_flyer_attack 70
wait 4500

upgrade 2 z_flyer_carapace 70
wait 4500

upgrade 3 z_flyer_attack 70
wait 4500

upgrade 3 z_flyer_carapace 70
stop

:block9
wait_train 12 zergling
upgrade 1 zergling_speed 70

:block32
notowns_jump hive block30
goto block31

:block30
wait 300

goto block32

:block31
wait_train 12 zergling
upgrade 1 zergling_attack 70
stop

:block8
wait_train 8 hydralisk
upgrade 1 hydralisk_speed 70
wait 2700


:block35
notowns_jump lair block33
goto block34

:block33
wait 300

goto block35

:block34
wait_train 12 hydralisk
tech lurker_aspect 70
wait 1800

place_guard lurker 0
place_guard lurker 1
place_guard lurker 2
wait_train 12 hydralisk
upgrade 1 hydralisk_range 70
stop

:block13
wait_train 12 hydralisk
upgrade 1 z_missile_attack 70
wait 4500

upgrade 1 z_carapace 70
wait 4500

wait_train 12 zergling
upgrade 1 z_melee_attack 70
wait 3600


:block38
notowns_jump lair block36
goto block37

:block36
wait 300

goto block38

:block37
wait_train 12 hydralisk
upgrade 2 z_missile_attack 70
wait 3600

upgrade 2 z_carapace 70
wait 3600

wait_train 12 zergling
upgrade 2 z_melee_attack 70
wait 3600


:block41
notowns_jump hive block39
goto block40

:block39
wait 300

goto block41

:block40
wait_train 12 hydralisk
upgrade 3 z_missile_attack 70
wait 3600

upgrade 3 z_carapace 70
wait 3600

wait_train 12 zergling
wait_train 1 ultralisk
upgrade 3 z_melee_attack 70
stop

:block11
wait_train 1 queen
tech spawn_broodling 80
wait 2700

tech ensnare 70
wait 2700

upgrade 1 queen_mana 30
stop

:block10
notowns_jump lair block42
goto block43

:block42
wait 300

goto block10

:block43
upgrade 1 overlord_speed 80
wait 2700

upgrade 1 overlord_capacity 80
wait 2700


:block46
notowns_jump hive block44
goto block45

:block44
wait 300

goto block46

:block45
upgrade 1 overlord_sight 30
stop

:block12
creep 4
build 5 creep_colony 70
wait_build 5 creep_colony
build 1 spore_colony 70
wait 450

creep 4
build 6 creep_colony 70
wait_build 6 creep_colony
build 2 spore_colony 70
wait 600

creep 4
build 7 creep_colony 70
wait_build 7 creep_colony
build 3 spore_colony 70
wait 750

creep 4
build 8 creep_colony 70
wait_build 8 creep_colony
build 4 spore_colony 70
wait 900

creep 4
build 9 creep_colony 70
wait_build 9 creep_colony
build 5 spore_colony 70
wait 1050

creep 4
build 10 creep_colony 70
wait_build 10 creep_colony
build 6 spore_colony 70
wait 1200

stop

:block6
start_town
build 1 hatchery 80
wait_build 1 hatchery
build 1 drone 80
wait_build 1 drone
build 2 drone 80
wait_build 2 drone
multirun block47
place_guard lurker 0
place_guard lurker 1
build 3 drone 80
wait_build 3 drone
build 4 drone 80
wait_build 4 drone
build 5 drone 80
wait_build 5 drone
build 6 drone 80
wait_build 6 drone
build 7 drone 80
wait_build 7 drone
build 8 drone 80
wait_build 8 drone
build 9 drone 80
wait_build 9 drone
build 10 drone 80
wait_build 10 drone

:block50
notowns_jump lair block48
goto block49

:block48
wait 300

goto block50

:block49
notowns_jump queen_nest block51
goto block52

:block51
wait 300

goto block49

:block52
player_need 1 queen_nest
place_guard queen 0
build 10 drone 80
wait_build 10 drone
build 11 drone 80
wait_build 11 drone
build 13 drone 80
wait_build 13 drone
build 14 drone 80
wait_build 14 drone
build 15 drone 80
wait_build 15 drone
build 16 drone 80
wait_build 16 drone
build 17 drone 80
wait_build 17 drone
build 18 drone 80
wait_build 18 drone
build 19 drone 80
wait_build 19 drone
build 20 drone 80
wait_build 20 drone
build 24 drone 80
wait_build 24 drone

:block55
notowns_jump hive block53
goto block54

:block53
wait 300

goto block55

:block54
notowns_jump defiler_mound block56
goto block57

:block56
wait 300

goto block54

:block57
place_guard defiler 0
stop

:block47
groundmap_jump block58

:block61
notowns_jump spawning_pool block59
goto block60

:block59
wait 300

goto block61

:block60
player_need 1 spawning_pool

:block64
notowns_jump hydralisk_den block62
goto block63

:block62
wait 300

goto block64

:block63
player_need 1 hydralisk_den

:block67
notowns_jump evolution_chamber block65
goto block66

:block65
wait 300

goto block67

:block66
player_need 1 evolution_chamber
creep 3
build 1 creep_colony 70
wait_build 1 creep_colony
build 1 sunken_colony 70
wait 450

creep 4
build 2 creep_colony 70
wait_build 2 creep_colony
build 1 spore_colony 70
wait 450

creep 4
build 3 creep_colony 70
wait_build 3 creep_colony
build 2 spore_colony 70
wait 450

creep 3
build 4 creep_colony 70
wait_build 4 creep_colony
build 2 sunken_colony 70
wait 900

creep 4
build 5 creep_colony 70
wait_build 5 creep_colony
build 3 spore_colony 70
wait 900

creep 4
build 6 creep_colony 70
wait_build 6 creep_colony
build 4 spore_colony 70
wait 900

creep 4
build 7 creep_colony 70
wait_build 7 creep_colony
build 5 spore_colony 70
wait 900

stop

:block58
notowns_jump spawning_pool block68
goto block69

:block68
wait 300

goto block58

:block69
player_need 1 spawning_pool
creep 3
build 1 creep_colony 70
wait_build 1 creep_colony
build 1 sunken_colony 70
wait 450

creep 3
build 2 creep_colony 70
wait_build 2 creep_colony
build 2 sunken_colony 70
wait 900


:block72
notowns_jump hydralisk_den block70
goto block71

:block70
wait 300

goto block72

:block71
player_need 1 hydralisk_den

:block75
notowns_jump evolution_chamber block73
goto block74

:block73
wait 300

goto block75

:block74
player_need 1 evolution_chamber
creep 4
build 3 creep_colony 70
wait_build 3 creep_colony
build 1 spore_colony 70
wait 900

creep 4
build 4 creep_colony 70
wait_build 4 creep_colony
build 2 spore_colony 70
wait 900

creep 4
build 5 creep_colony 70
wait_build 5 creep_colony
build 3 spore_colony 70
wait 900

stop

:block2
define_max 30 drone
define_max 12 hydralisk
define_max 10 zergling
define_max 37 mutalisk
define_max 10 scourge
define_max 5 lurker
define_max 6 queen
define_max 6 defiler
define_max 8 guardian
define_max 12 devourer
define_max 255 ultralisk
build 1 drone 150
wait_buildstart 1 drone
build 1 hatchery 150
wait_buildstart 1 hatchery
build 1 overlord 130
wait_buildstart 1 overlord
build 9 drone 80
wait_buildstart 9 drone
build 2 overlord 80
wait_buildstart 2 overlord
build 1 extractor 80
wait_buildstart 1 extractor
build 13 drone 80
wait_buildstart 13 drone
build 2 hatchery 80
wait_buildstart 2 hatchery
build 1 spawning_pool 80
wait_buildstart 1 spawning_pool
build 18 drone 80
wait_buildstart 18 drone
build 3 overlord 80
wait_buildstart 3 overlord
random_jump 64 block76
farms_timing
build 1 lair 80
wait_buildstart 1 lair

:block82
creep 4
build 1 creep_colony 70
wait_buildstart 1 creep_colony
build 2 creep_colony 70
wait_buildstart 2 creep_colony
build 18 drone 80
wait_buildstart 18 drone
build 3 creep_colony 70
wait_buildstart 3 creep_colony
build 4 creep_colony 70
wait_buildstart 4 creep_colony
build 1 spire 80
wait_buildstart 1 spire
multirun block14
build 1 evolution_chamber 80
wait_buildstart 1 evolution_chamber
build 20 drone 80
wait_buildstart 20 drone
upgrade 1 overlord_capacity 80
build 2 hatchery 80
wait_buildstart 2 hatchery
build 30 drone 80
wait_buildstart 30 drone
build 1 hydralisk_den 80
wait_buildstart 1 hydralisk_den
defenseclear_gg
defensebuild_gg 1 mutalisk
defenseuse_gg 1 mutalisk
defensebuild_gg 1 zergling
defenseuse_gg 1 zergling
defensebuild_gg 1 hydralisk
defenseuse_gg 1 hydralisk
defensebuild_gg 1 guardian
defenseuse_gg 1 guardian
defenseuse_gg 1 lurker
defenseuse_gg 1 ultralisk
defenseclear_ag
defensebuild_ag 1 mutalisk
defenseuse_ag 1 mutalisk
defensebuild_ag 1 hydralisk
defenseuse_ag 1 hydralisk
defensebuild_aa 1 devourer
defenseuse_aa 1 devourer
defensebuild_aa 2 scourge
defenseuse_aa 2 scourge
defensebuild_aa 1 mutalisk
defenseuse_aa 1 mutalisk
defensebuild_ga 1 mutalisk
defenseuse_ga 1 mutalisk
defensebuild_ga 1 guardian
defenseuse_ga 1 guardian
train 4 mutalisk
multirun block77
train 10 mutalisk
panic block6
expand 1 block6
upgrade 1 overlord_speed 80
train 14 mutalisk
build 1 queen_nest 80
wait_buildstart 1 queen_nest
upgrade 1 overlord_sight 70
train 18 mutalisk
build 1 hive 80
wait_buildstart 1 hive
train 20 mutalisk
expand 2 block6
build 1 greater_spire 80
wait_buildstart 1 greater_spire
train 24 mutalisk
train 1 guardian
train 2 devourer
train 23 mutalisk
train 2 guardian
train 4 devourer
train 22 mutalisk
train 3 guardian
train 6 devourer
train 21 mutalisk
train 4 guardian
train 7 devourer
train 20 mutalisk
train 5 guardian
train 8 devourer
train 18 mutalisk
train 6 guardian
place_guard queen 0
place_guard queen 1
place_guard queen 2
multirun block78
train 24 mutalisk
train 8 devourer
train 6 scourge
train 6 guardian
wait_train 6 guardian
attack_do
attack_clear
attack_add 12 mutalisk
attack_add 6 devourer
attack_add 6 scourge
attack_add 6 guardian
attack_prepare
build 1 defiler_mound 80
wait_buildstart 1 defiler_mound
multirun block15
multirun block8
multirun block13
multirun block16

:block81
attack_prepare
wait 300

attack_do
attack_clear
resources_jump 2100 2400 block79
resources_jump 1600 1600 block80
wait 1800

goto block81

:block79
train 14 mutalisk
train 6 devourer
train 14 mutalisk
train 6 guardian
wait_train 6 guardian
attack_add 12 mutalisk
attack_add 6 guardian
attack_add 6 devourer
goto block81

:block80
train 20 mutalisk
train 6 devourer
wait_train 6 devourer
attack_add 14 mutalisk
attack_add 6 devourer
goto block81

:block77
build 4 spore_colony 80
wait_build 4 spore_colony
creep 4
build 5 creep_colony 70
wait_build 5 creep_colony
build 5 spore_colony 70
wait 450

creep 4
build 6 creep_colony 70
wait_build 6 creep_colony
build 6 spore_colony 70
wait 600

creep 4
build 7 creep_colony 70
wait_build 7 creep_colony
build 7 spore_colony 70
wait 750

creep 4
build 8 creep_colony 70
wait_build 8 creep_colony
build 8 spore_colony 70
wait 450

creep 3
build 9 creep_colony 70
wait_build 9 creep_colony
build 1 sunken_colony 70
wait 900

creep 3
build 10 creep_colony 70
wait_build 10 creep_colony
build 2 sunken_colony 70
wait 900

stop

:block78
wait_train 1 queen
tech ensnare 70
wait 2700

tech spawn_broodling 70
wait 2700

upgrade 1 queen_mana 30
stop

:block76
define_max 20 hydralisk
build 2 lair 80
wait_buildstart 2 lair
build 1 hydralisk_den 80
wait_buildstart 1 hydralisk_den
build 22 drone 80
wait_buildstart 22 drone
build 5 overlord 80
wait_buildstart 5 overlord
farms_timing
upgrade 1 overlord_capacity 80
upgrade 1 overlord_speed 80
defenseuse_gg 1 zergling
defenseuse_gg 1 hydralisk
defenseuse_ag 1 hydralisk
train 16 hydralisk
wait_train 16 hydralisk
attack_clear
attack_add 16 hydralisk
attack_prepare
train 20 hydralisk
define_max 12 hydralisk
goto block82
