# stat_txt.tbl entry 1342: Terran Expansion Custom Level<0>
TMCx(1342, 101, aiscript):
    debug(t3, t3 is going.)
    --t3--
	start_town()
	transports_off()
	farms_notiming()
	defaultbuild_off()
    define_max(100, Terran SCV)
	define_max(48, Terran Marine)
	define_max(8, Terran Medic)
	define_max(4, Terran Firebat)
	define_max(12, Terran Siege Tank<0>Tank Mode)
	define_max(255, Terran Goliath)
	define_max(255, Terran Wraith)
	define_max(255, Terran Dropship)
	define_max(33, Terran Battlecruiser)
	define_max(2, Terran Science Vessel)
	define_max(255, Terran Valkyrie)
	define_max(255, Terran Ghost)
	define_max(255, Nuclear Missile)
	define_max(255, Terran Vulture)
	build(1, Terran Command Center, 150)
	wait_build(1, Terran Command Center)
	build(4, Terran SCV, 130)
	wait_buildstart(4, Terran SCV)
	build(8, Terran SCV, 80)
	wait_buildstart(8, Terran SCV)
	build(1, Terran Supply Depot, 80)
	wait_buildstart(1, Terran Supply Depot)
	build(12, Terran SCV, 80)
	wait_build(12, Terran SCV)
	build(1, Terran Barracks, 80)
	wait_buildstart(1, Terran Barracks)
	build(13, Terran SCV, 80)
	wait_buildstart(13, Terran SCV)
	build(2, Terran Barracks, 80)
	build(14, Terran SCV, 80)
	wait_buildstart(14, Terran SCV)
	build(3, Terran Barracks, 80)
	wait_buildstart(3, Terran Barracks)
	farms_timing()
    build(1, Terran Refinery, 80)
	multirun(TMCx 0000)
	wait_force(3, Terran Marine)
	defensebuild_gg(1, Terran Marine)
	defenseuse_gg(1, Terran Marine)
	build(1, Terran Bunker, 80)
	wait_force(12, Terran Marine)
	build(2, Terran Bunker, 80)
	wait_force(18, Terran Marine)
    multirun(morekuang)
	build(1, Terran Academy, 80)
	wait_buildstart(1, Terran Academy)
	multirun(gastrick)
	# build(2, Terran Refinery, 80)
	#capt_expand()
	defensebuild_ag(1, Terran Marine)
	defenseuse_ag(1, Terran Marine)
	defensebuild_gg(1, Terran Firebat)
	defenseuse_gg(1, Terran Firebat)
	defensebuild_gg(1, Terran Medic)
	defenseuse_gg(1, Terran Medic)
	wait_force(2, Terran Medic)
	wait_force(2, Terran Firebat)
	wait_force(18, Terran Marine)
    
	multirun(TMCx 0001) # 开矿
	build(4, Terran Barracks, 80)
	wait_buildstart(4, Terran Barracks)
	multirun(TMCx 0002)
	multirun(TMCx 0003)
	multirun(TMCx 0004)
	goto(TMCx 0005)


		--TMCx 0005--
	build(1, Terran Factory, 80)
	wait_build(1, Terran Factory)
    multirun(r_tank)
	build(1, Terran Starport, 80)
	wait_build(1, Terran Starport)
	build(1, Terran Science Facility, 80)
	wait_build(1, Terran Science Facility)
	build(1, Terran Control Tower, 80)
	wait_buildstart(1, Terran Control Tower)
	build(1, Terran Physics Lab, 80)
	wait_buildstart(1, Terran Physics Lab)
	wait_force(1, Terran Science Vessel)
    # 第2个机场 (基础 155/105 + 冗余)
--check_vs2--
    resources_jump(155, 155, exec_vs2)
    wait(60)
    goto(check_vs2)
--exec_vs2--
    build(2, Terran Starport, 80)
    wait_buildstart(2, Terran Starport)
    build(2, Terran Control Tower, 80)

    # 第3个机场 (门槛: 255/255)
--check_vs3--
    resources_jump(255, 255, exec_vs3)
    wait(60)
    goto(check_vs3)
--exec_vs3--
    build(3, Terran Starport, 80)
    wait_buildstart(3, Terran Starport)
    build(3, Terran Control Tower, 80)

    # 第4个机场 (门槛: 355/355)
--check_vs4--
    resources_jump(355, 355, exec_vs4)
    wait(60)
    goto(check_vs4)
--exec_vs4--
    build(4, Terran Starport, 80)
    wait_buildstart(4, Terran Starport)
    build(4, Terran Control Tower, 80)
    
	wait_force(1, Terran Battlecruiser)
	multirun(TMCx 0006)
	defensebuild_aa(1, Terran Battlecruiser)
	defenseuse_aa(1, Terran Battlecruiser)
	defensebuild_ga(1, Terran Battlecruiser)
	defenseuse_ga(1, Terran Battlecruiser)
	defensebuild_ag(1, Terran Battlecruiser)
	defenseuse_ag(1, Terran Battlecruiser)
	defensebuild_gg(1, Terran Battlecruiser)
	defenseuse_gg(1, Terran Battlecruiser)
	multirun(TMCx 0007)
	multirun(TMCx 0008)
	goto(TMCx 0009)
    
        --r_tank--
    build(1, Terran Machine Shop, 80)
	wait_build(1, Terran Machine Shop)
    defensebuild_gg(1, Terran Siege Tank<0>Tank Mode)
    defenseuse_gg(1, Terran Siege Tank<0>Tank Mode)
    tech(Tank Siege Mode, 80)
    stop()

		--TMCx 0009--
	wait_force(1, Terran Science Vessel)
	wait_force(7, Terran Battlecruiser)
	
	attack_add(1, Terran Science Vessel)
	attack_add(6, Terran Battlecruiser)
	attack_prepare()
	wait(200)
	attack_do()    
	send_suicide(0)
	wait(200)
    multirun(morekuang)
    wait(700)
    attack_clear()
	goto(TMCx 0009)

    	--morekuang--
	resources_jump(400, 0, newkuang)
	wait(75)
	goto(morekuang)
	--newkuang--
	resources_jump(8000, 8000, nokuang)
	expand(99, TMCx 0010)
	--nokuang--
	wait(75)
	stop()

		--TMCx 0002--                      
	build(5, Terran Barracks, 80)
	wait_buildstart(5, Terran Barracks)
	build(6, Terran Barracks, 80)
	wait_buildstart(6, Terran Barracks)
	#build(7, Terran Barracks, 80)
	#wait_buildstart(7, Terran Barracks)
	#build(8, Terran Barracks, 80)
	#wait_buildstart(8, Terran Barracks)
	stop()


		--TMCx 0008--
    # 第5个机场 (门槛: 455/455)
--check_vs5--
    resources_jump(455, 455, exec_vs5)
    wait(60)
    goto(check_vs5)
--exec_vs5--
    build(5, Terran Starport, 80)
    wait_buildstart(5, Terran Starport)
    build(5, Terran Control Tower, 80)

    # 第6个机场 (门槛: 555/555)
--check_vs6--
    resources_jump(555, 555, exec_vs6)
    wait(60)
    goto(check_vs6)
--exec_vs6--
    build(6, Terran Starport, 80)
    wait_buildstart(6, Terran Starport)
    build(6, Terran Control Tower, 80)
	stop()


		--TMCx 0007--
    resources_jump(8000,8000,TMCx 0007a)
	expand(99, TMCx 0010)
	
        --TMCx 0007a--
    wait(3600)
	goto(TMCx 0007)


		--TMCx 0010--
	start_town()
	build(1, Terran Command Center, 80)
	wait_build(1, Terran Command Center)
	build(1, Terran SCV, 80)
	wait_build(1, Terran SCV)
	build(2, Terran SCV, 80)
	wait_build(2, Terran SCV)
	build(3, Terran SCV, 80)
	wait_build(3, Terran SCV)
    build(1, Terran Refinery, 20)
	build(5, Terran SCV, 80)
	wait_build(5, Terran SCV)
	build(7, Terran SCV, 80)
	wait_build(7, Terran SCV)
    build(9, Terran SCV, 80)
	wait_build(9, Terran SCV)
	build(11, Terran SCV, 80)
	wait_build(11, Terran SCV)
	build(13, Terran SCV, 80)
	wait_build(13, Terran SCV)
	build(14, Terran SCV, 80)
	wait_build(14, Terran SCV)
    stop()

		--TMCx 0000--
	build(17, Terran SCV, 80)
	wait_build(17, Terran SCV)
	build(19, Terran SCV, 80)
	wait_build(19, Terran SCV)
	build(21, Terran SCV, 80)
	wait_build(21, Terran SCV)
	build(23, Terran SCV, 80)
	wait_build(23, Terran SCV)
	build(25, Terran SCV, 80)
	wait_build(25, Terran SCV)
	build(27, Terran SCV, 80)
	wait_build(27, Terran SCV)
	build(30, Terran SCV, 80)
	wait_build(30, Terran SCV)
    --scv50--
    wait_force(50, Terran SCV)
    wait(600)
    goto(scv50)

		--TMCx 0003--
	wait_force(4, Terran Marine)
	wait_build(1, Terran Academy)
	wait_force(2, Terran Medic)
	wait_force(2, Terran Firebat)
	wait_force(12, Terran Marine)
	wait_force(4, Terran Medic)
	wait_force(36, Terran Marine)
	wait(400)

	goto(TMCx 0003)


		--TMCx 0001--
	expand(1, TMCx 0012)
	stop()


		--TMCx 0012--
	start_town()
	build(1, Terran Command Center, 80)
	wait_build(1, Terran Command Center)
	build(2, Terran SCV, 80)
	wait_build(2, Terran SCV)
	build(4, Terran SCV, 80)
	wait_build(4, Terran SCV)
	build(1, Terran Refinery, 20)
	build(6, Terran SCV, 80)
	wait_build(6, Terran SCV)
    resources_jump(10000,0,leida)
	build(8, Terran SCV, 80)
	wait_build(8, Terran SCV)	
	build(10, Terran SCV, 80)
	wait_build(10, Terran SCV)
	build(12, Terran SCV, 80)
	wait_build(12, Terran SCV)
    build(14, Terran SCV, 80)
	wait_build(14, Terran SCV)
    --leida--
    build(1, Terran Comsat Station, 80)
	wait_build(1, Terran Comsat Station)
    stop()

		--TMCx 0004--
	wait_build(1, Terran Academy)
	build(1, Terran Comsat Station, 80)
	wait_buildstart(1, Terran Comsat Station)
	tech(Stim Packs, 70)
    wait_train(12, Terran Marine)
	upgrade(1, U-238 Shells, 70)
	build(2, Terran Engineering Bay, 80)
	wait_build(2, Terran Engineering Bay)
    wait_train(12, Terran Marine)
	upgrade(1, Terran Infantry Weapons, 70)
	upgrade(1, Terran Infantry Armor, 70)
	wait(4500)
    wait_train(12, Terran Marine)
	upgrade(2, Terran Infantry Weapons, 70)
	upgrade(2, Terran Infantry Armor, 70)
	wait(4500)
    wait_train(12, Terran Marine)
	upgrade(3, Terran Infantry Weapons, 70)
	upgrade(3, Terran Infantry Armor, 70)
	stop()


		--TMCx 0006--
	wait_force(4, Terran Battlecruiser)
	build(2, Terran Armory, 80)
	wait_build(2, Terran Armory)
    wait_train(6, Terran Battlecruiser)
	upgrade(1, Terran Ship Weapons, 70)
	upgrade(1, Terran Ship Plating, 70)
	wait(4500)

	wait_build(1, Terran Science Facility)
    wait_train(6, Terran Battlecruiser)
	upgrade(2, Terran Ship Plating, 70)
	upgrade(2, Terran Ship Weapons, 70)
	tech(Yamato Gun, 70)
	wait(4500)

	wait_force(6, Terran Battlecruiser)
	wait(4500)

	upgrade(3, Terran Ship Plating, 70)
	upgrade(3, Terran Ship Weapons, 70)
	upgrade(1, Colossus Reactor, 30)    
    wait(4500)
    wait_train(6, Terran Siege Tank<0>Tank Mode)
    upgrade(1, Terran Vehicle Plating, 70)
	upgrade(1, Terran Vehicle Weapons, 70)
	wait(4500)
    
	wait_build(1, Terran Science Facility)
    wait_train(6, Terran Siege Tank<0>Tank Mode)
	upgrade(2, Terran Vehicle Plating, 70)
	upgrade(2, Terran Vehicle Weapons, 70)
	wait(4500)
    
    wait_train(6, Terran Siege Tank<0>Tank Mode)
	upgrade(3, Terran Vehicle Plating, 70)
	upgrade(3, Terran Vehicle Weapons, 70)
	stop()

    --gastrick--    
    upgrade(1, Metabolic Boost, 10)
    wait_train(20, Terran SCV)
    
    tech(Plague, 10)
    upgrade(1, Ventral Sacs, 10)
    tech(Lurker Aspect, 10)
    upgrade(1, Adrenal Glands, 10)
    upgrade(1, Anabolic Synthesis, 10)
    stop()