# stat_txt.tbl entry 1344: Zerg Expansion Custom Level<0>
ZMCx(1344, 101, aiscript):
    debug(z1, z1 is going.)
    --z1--
    start_town()
    transports_off()
    farms_notiming()
    defaultbuild_off()
    default_min(0)
    goto(dl0)
    
    --dl0--
	define_max(9, Zerg Hydralisk)
	define_max(18, Zerg Zergling)
	define_max(100, Zerg Mutalisk)
	define_max(12, Zerg Scourge)
	define_max(12, Zerg Lurker)
	define_max(6, Zerg Queen)
	define_max(6, Zerg Defiler)
	define_max(60, Zerg Guardian)
	define_max(18, Zerg Devourer)
	define_max(12, Zerg Ultralisk)
    goto(dl1)
    
    --dl1--
    build(1, Zerg Drone, 150)
	wait_buildstart(1, Zerg Drone)
	build(1, Zerg Hatchery, 150)
	wait_buildstart(1, Zerg Hatchery)
	build(1, Zerg Overlord, 130)
	wait_buildstart(1, Zerg Overlord)
	build(9, Zerg Drone, 80)
	wait_buildstart(9, Zerg Drone)
    build(2, Zerg Overlord, 80)
	wait_buildstart(2, Zerg Overlord)
    build(12, Zerg Drone, 80)
	wait_buildstart(12, Zerg Drone)
    multirun(kuang2)    
    goto(dl2)
    
    --kuang2--
    expand(1, ZMCx 0065)
    stop()
    
    --ZMCx 0065--
    start_town()
    build(1, Zerg Hatchery, 80)
    wait_build(1, Zerg Hatchery)
    defenseuse_gg(2, Zerg Zergling)
    defenseuse_gg(1, Zerg Hydralisk)
    defenseuse_ag(1, Zerg Hydralisk)
    build(1, Zerg Drone, 80)    
    wait_build(1, Zerg Drone)
    wait(750)
    build(4, Zerg Drone, 80)
    wait_build(4, Zerg Drone)
    creep(3)
	build(2, Zerg Creep Colony, 80)
	wait_buildstart(2, Zerg Creep Colony)
    build(3, Zerg Drone, 80)
    wait_build(3, Zerg Drone)
    build(4, Zerg Drone, 80)
    wait_build(4, Zerg Drone)
	build(2, Zerg Sunken Colony, 80)
    wait(750)
    build(7, Zerg Drone, 80)
    wait_build(7, Zerg Drone)
    wait(750)
    build(10, Zerg Drone, 80)
    wait_build(10, Zerg Drone)
    wait(750)
    build(13, Zerg Drone, 80)
    wait_build(13, Zerg Drone)
    stop()
    
    --ZMCx 0066--
    start_town()
    build(1, Zerg Hatchery, 80)
    wait_build(1, Zerg Hatchery)
    defenseuse_gg(2, Zerg Zergling)
    defenseuse_gg(1, Zerg Hydralisk)
    defenseuse_ag(1, Zerg Hydralisk)
    build(1, Zerg Drone, 80)    
    wait_build(1, Zerg Drone)
    wait(750)
    build(4, Zerg Drone, 80)
    wait_build(4, Zerg Drone)
    wait(750)
    build(7, Zerg Drone, 80)
    wait_build(7, Zerg Drone)
    wait(750)
    build(10, Zerg Drone, 80)
    wait_build(10, Zerg Drone)
    wait(750)
    build(13, Zerg Drone, 80)
    wait_build(13, Zerg Drone)
    stop()
    
    --dl2--
    build(1, Zerg Spawning Pool, 80)
    wait_buildstart(1, Zerg Spawning Pool)
    build(13, Zerg Drone, 80)
    wait_buildstart(13, Zerg Drone)
    build(2, Zerg Hatchery, 80)
    wait_buildstart(2, Zerg Hatchery)
    build(13, Zerg Drone, 80)
    wait_buildstart(13, Zerg Drone)
    build(1, Zerg Extractor, 80)
    wait_buildstart(1, Zerg Extractor)
    build(16, Zerg Drone, 80)
    wait_buildstart(16, Zerg Drone)
    build(3, Zerg Hatchery, 80)
    wait_buildstart(3, Zerg Hatchery)
    
    farms_timing()
    
    multirun(drone30)

    defensebuild_gg(2, Zerg Zergling)
    defenseuse_gg(2, Zerg Zergling)
    build(1, Zerg Hydralisk Den, 80)
    wait_buildstart(1, Zerg Hydralisk Den)
    defensebuild_ag(1, Zerg Hydralisk)
    defenseuse_ag(1, Zerg Hydralisk)
    defensebuild_gg(1, Zerg Hydralisk)
    defenseuse_gg(1, Zerg Hydralisk)
    wait_force(12, Zerg Zergling)
    wait_force(6, Zerg Hydralisk)
    multirun(jidi4a)
    wait_force(30, Zerg Drone)
    multirun(gastrick)
    multirun(morekoushui)
    multirun(r_koushui)
    goto(dl3)
    
    --drone30--
	build(18, Zerg Drone, 80)
	wait_build(18, Zerg Drone)
	build(20, Zerg Drone, 80)
	wait_build(20, Zerg Drone)
	build(23, Zerg Drone, 80)
	wait_build(23, Zerg Drone)  
	build(26, Zerg Drone, 80)
	wait_build(26, Zerg Drone)
	build(28, Zerg Drone, 80)
	wait_build(28, Zerg Drone)
	build(30, Zerg Drone, 80)
	wait_build(30, Zerg Drone)
    stop()
    
    --morekoushui--
    wait_force(18, Zerg Zergling)
    wait_force(9, Zerg Hydralisk)
    wait(500)
    goto(morekoushui)
    
    --jidi4a--
    resources_jump(800, 0, jidi4)
    wait(75)
    goto(jidi4a)
    --jidi4--
    build(4, Zerg Hatchery, 80)
    wait_buildstart(4, Zerg Hatchery)
    wait_force(40, Zerg Drone)
    --jidi5a--
    resources_jump(1000, 0, jidi5)
    wait(75)
    goto(jidi5a)
    --jidi5--
    build(5, Zerg Hatchery, 80)
    wait_buildstart(5, Zerg Hatchery)
    wait_force(40, Zerg Drone)
    --jidi6a--
    resources_jump(1500, 0, jidi6)
    wait(100)
    goto(jidi6a)
    --jidi6--
    build(6, Zerg Hatchery, 80)
    wait_buildstart(6, Zerg Hatchery)
    wait_force(40, Zerg Drone)
    --jidi7a--
    resources_jump(2000, 0, jidi7)
    wait(100)
    goto(jidi7a)
    --jidi7--
    build(7, Zerg Hatchery, 80)
    wait_buildstart(7, Zerg Hatchery)
    wait_force(40, Zerg Drone)
     --jidi8a--
    resources_jump(2500, 0, jidi8)
    wait(100)
    goto(jidi8a)
    --jidi8--
    build(8, Zerg Hatchery, 80)
    wait_buildstart(8, Zerg Hatchery)
    --jidi9a--
    resources_jump(3000, 0, jidi9)
    wait(100)
    goto(jidi9a)
    --jidi9--
    build(9, Zerg Hatchery, 80)
    wait_buildstart(9, Zerg Hatchery)
    wait_force(40, Zerg Drone)
    stop()
    
    --r_koushui--
    wait_build(1, Zerg Spawning Pool) 
    upgrade(1, Metabolic Boost, 70)
    wait_build(1, Zerg Hydralisk Den)
    upgrade(1, Muscular Augments, 70)    
    wait(3000)
    upgrade(1, Grooved Spines, 70)
    
    build(2, Zerg Evolution Chamber, 80)
    wait_build(2, Zerg Evolution Chamber)
    
    wait_train(12, Zerg Hydralisk)
    upgrade(1, Zerg Carapace, 70)
    upgrade(1, Zerg Missile Attacks, 70)
    wait(4500)
    
    wait_build(1, Zerg Lair)
    wait_train(12, Zerg Hydralisk)
    upgrade(2, Zerg Carapace, 70)
    upgrade(2, Zerg Missile Attacks, 70)
    wait(4500)
    
    wait_build(1, Zerg Hive)
    wait_train(12, Zerg Hydralisk)
    upgrade(3, Zerg Carapace, 70)
    upgrade(3, Zerg Missile Attacks, 70)
    stop()
    
    --dl3--
    build(1, Zerg Lair, 80)
    wait_build(1, Zerg Lair)
    build(1, Zerg Queen's Nest, 80)
    wait_build(1, Zerg Queen's Nest)
    build(1, Zerg Hive, 80)
    wait_buildstart(1, Zerg Hive)
    build(1, Zerg Spire, 80)
    wait_buildstart(1, Zerg Spire)
    wait_build(1, Zerg Hive)
    build(1, Zerg Greater Spire, 80)
    wait_buildstart(1, Zerg Greater Spire)
    multirun(gf_vs)
    defensebuild_aa(1, Zerg Devourer)
    defenseuse_aa(1, Zerg Devourer)
    defensebuild_ag(1, Zerg Devourer)
    defenseuse_ag(1, Zerg Devourer)
    defensebuild_ga(1, Zerg Guardian)
    defenseuse_ga(1, Zerg Guardian)
    defensebuild_gg(1, Zerg Guardian)
    defenseuse_gg(1, Zerg Guardian)
    multirun(r_3ben)    
    multirun(morekuang)    
    goto(final_attack)
    
    --r_3ben--
    upgrade(1, Adrenal Glands, 70)
    wait(1200)
    upgrade(1, Pneumatized Carapace, 70)
    stop()
    
    --morekuang--
    expand(99, ZMCx 0066)
    wait(2400)
    goto(morekuang)
    
    --final_attack--    
    wait_force(2, Zerg Guardian)
    wait_force(2, Zerg Devourer)
    wait_force(4, Zerg Guardian)
    wait_force(4, Zerg Devourer)
    wait_force(6, Zerg Guardian)
    wait_force(6, Zerg Devourer) 
    wait_force(12, Zerg Guardian)
    attack_clear()
    wait_force(12, Zerg Guardian)
    attack_add(12, Zerg Guardian)
    wait_force(6, Zerg Devourer)
    attack_add(6, Zerg Devourer)  
    attack_prepare()
    wait(500)
    #attack_do()
    wait(24)
    send_suicide(0)
    goto(final_attack)    
    
    --gf_vs--
    build(2, Zerg Spire, 70)
    wait_build(2, Zerg Spire)
    wait_build(1, Zerg Greater Spire)
    wait_train(6, Zerg Devourer)
    upgrade(1, Zerg Flyer Carapace, 70)
    upgrade(1, Zerg Flyer Attacks, 70)
    wait(5000)
    wait_train(6, Zerg Devourer)
    upgrade(2, Zerg Flyer Carapace, 70)
    upgrade(2, Zerg Flyer Attacks, 70)
    wait(5000)
    wait_train(6, Zerg Devourer)
    upgrade(3, Zerg Flyer Carapace, 70)
    upgrade(3, Zerg Flyer Attacks, 70)
    wait(4500)
    wait_train(12, Zerg Zergling)
    upgrade(1, Zerg Melee Attacks, 70)
    wait(3600)
    wait_train(12, Zerg Zergling)
    upgrade(2, Zerg Melee Attacks, 70)
    wait(3600)
    wait_train(12, Zerg Zergling)
    upgrade(3, Zerg Melee Attacks, 70)
    wait(3600)
    stop()    
    
    --gastrick--
    tech(Stim Packs, 10) # Academy # 100/100 # 1200 # 兴奋剂
    wait_build(20, Zerg Drone)
    tech(EMP Shockwave, 10) # Science Facility # 200/200 # 1200 # EMP震荡波
    tech(Irradiate, 10)
    upgrade(1, U-238 Shells, 10)
    tech(Restoration, 10)
    tech(Optical Flare, 10)
    tech(Irradiate, 10)
    stop()